### ISSUE TITLE
Include plugin within theme

### ISSUE THREAD

**Issue by jackfearing** [tmconnect/ACF-RGBA-Color-Field#1]
Hello, does this work with ACF Flexible fields? I'm linking to the files via the functions.php method. I see the field option when adding a field however when I go to the page to select the color values all I have is a text box. When I activate the plugin via the plugins menu it works fine. Is the functions.php method different? I'm also running ACF Pro 5.4.5

Thanks,
Jack

**Comment by tmconnect** [comment]
Hello Jack,

sorry, for the late reply...

This has nothing to do with flexible fields. It's a bug in the version you are using.

Please take a try with the new version. This is a re-written versions and if you take a look at the readme, you will see how to implement the plugin within your theme.

Cheers
Thomas
