### ISSUE TITLE
Field type does not exist

### ISSUE THREAD

**Issue by PthPndr** [tmconnect/ACF-RGBA-Color-Field#2]
Quick question.

Should v2.1 be a direct replacement for 2.0 or will I need to re-select the field everywhere I used it?

Currently, I can create a new field with no problems but all my existing fields say the field type does not exist. If I go back to v2.0 the fields return. (There were no issues upgrading from v1.0 to v2.0)

**Comment by tmconnect** [comment]
Sorry, that's my fault. The version 2.1 got a wrong internal ACF name than V 2.0. I fixed this with V 2.1.1

Thomas

**Comment by PthPndr** [comment]
Thanks, no worries there. 

I tried it again and I no longer receive that error but now all I get is a "text box" instead of the picker. I checked and it is the same on all new and old fields.

**Comment by tmconnect** [comment]
Sorry again - I missed to change the field name/field type in the JS file as well. Fixed with V 2.1.2
